# Generated by Django 3.0.7 on 2020-06-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Título')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('data_expiracao', models.DateField(verbose_name='Data de Expiração')),
                ('prioridade', models.CharField(choices=[('N', 'Normal'), ('A', 'Alta'), ('B', 'Baixa')], max_length=1, verbose_name='Prioridade')),
            ],
            options={
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
